/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serpientesescaleras.interfazGrafica;

/**
 *
 * @author CIROSS
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblBienvenida = new javax.swing.JLabel();
        jLbTitulo = new javax.swing.JLabel();
        jBtnPartida = new javax.swing.JButton();
        jBtnJugadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    //  jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblBienvenida.setText("Bienvenidos a:");
        jPanel1.add(jLblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 100, 450, -1));

        jLbTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbTitulo.setText("Serpientes y Escaleras");
        jPanel1.add(jLbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 450, -1));

        jBtnPartida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPartida.setText("Iniciar Partida");
        jBtnPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 30));

        jBtnJugadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnJugadores.setText("Ver Jugadores");
        jBtnJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJugadoresActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJugadoresActionPerformed
        JugadoresFrm tabla = new JugadoresFrm();
        tabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnJugadoresActionPerformed

    private void jBtnPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPartidaActionPerformed
        Juego juego = new Juego();
        juego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnPartidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnJugadores;
    private javax.swing.JButton jBtnPartida;
    private javax.swing.JLabel jLbTitulo;
    private javax.swing.JLabel jLblBienvenida;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
