/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serpientesescaleras.interfazGrafica;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author CIROSS
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        ImageIcon icono = new ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/Serpiente.png"));
        setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblBienvenida = new javax.swing.JLabel();
        jBtnPartida = new javax.swing.JButton();
        jBtnJugadores = new javax.swing.JButton();
        jLbTitulo = new javax.swing.JLabel();
        jLbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serpientes y Escaleras");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblBienvenida.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jLblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblBienvenida.setText("Bienvenidos a:");
        jPanel1.add(jLblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 490, -1));

        jBtnPartida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPartida.setText("Iniciar Partida");
        jBtnPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 30));

        jBtnJugadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnJugadores.setText("Ver Jugadores");
        jBtnJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJugadoresActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 30));

        jLbTitulo.setFont(new java.awt.Font("Comic Sans MS", 3, 30)); // NOI18N
        jLbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbTitulo.setText("Serpientes y Escaleras");
        jPanel1.add(jLbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 490, -1));

        jLbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/lago-cueva-serpientes.jpg"))); // NOI18N
        jPanel1.add(jLbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJugadoresActionPerformed
        JugadoresFrm tabla = new JugadoresFrm();
        tabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnJugadoresActionPerformed

    private void jBtnPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPartidaActionPerformed
        Juego juego = new Juego();
        juego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnPartidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnJugadores;
    private javax.swing.JButton jBtnPartida;
    private javax.swing.JLabel jLbFondo;
    private javax.swing.JLabel jLbTitulo;
    private javax.swing.JLabel jLblBienvenida;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
