/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serpientesescaleras.interfazGrafica;

import java.util.Random;
import serpientesescaleras.tablero.Tablero;

/**
 *
 * @author CIROSS
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLbDado = new javax.swing.JLabel();
        jBtnLanzar = new javax.swing.JButton();
        jBtnDetener = new javax.swing.JButton();
        jLbFilas = new javax.swing.JLabel();
        jTxtNumFilas = new javax.swing.JTextField();
        jLbColumnas = new javax.swing.JLabel();
        jTxtNumColumnas = new javax.swing.JTextField();
        jBtnCrearTablero = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuIr = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenuItemJugadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(255, 204, 153));
        jPanel.setOpaque(false);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jTable.setBackground(new java.awt.Color(255, 102, 51));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLbDado.setBackground(new java.awt.Color(255, 255, 255));
        jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado 6.jpg"))); // NOI18N

        jBtnLanzar.setText("Lanzar");
        jBtnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLanzarActionPerformed(evt);
            }
        });

        jBtnDetener.setText("Detener");
        jBtnDetener.setEnabled(false);
        jBtnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDetenerActionPerformed(evt);
            }
        });

        jLbFilas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbFilas.setText("Filas:");

        jTxtNumFilas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtNumFilas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLbColumnas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbColumnas.setText("Columnas:");

        jTxtNumColumnas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtNumColumnas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jBtnCrearTablero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnCrearTablero.setText("Crear Tablero");
        jBtnCrearTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearTableroActionPerformed(evt);
            }
        });

        jMenuIr.setText("Ir a ...");

        jMenuItemInicio.setText("Inicio");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenuIr.add(jMenuItemInicio);

        jMenuItemJugadores.setText("Ver Jugadores");
        jMenuItemJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJugadoresActionPerformed(evt);
            }
        });
        jMenuIr.add(jMenuItemJugadores);

        jMenuBar1.add(jMenuIr);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbFilas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNumFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLbColumnas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNumColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnCrearTablero))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnLanzar)
                                .addGap(8, 8, 8)
                                .addComponent(jBtnDetener)))
                        .addGap(114, 114, 114))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLbFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtNumFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtNumColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnCrearTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLbDado)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnLanzar)
                            .addComponent(jBtnDetener)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLanzarActionPerformed
        jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado gif dorado.gif")));
        jBtnLanzar.setEnabled(false);
        jBtnDetener.setEnabled(true);
    }//GEN-LAST:event_jBtnLanzarActionPerformed

    Random rnd = new Random();
    private void jBtnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDetenerActionPerformed
        int dado = rnd.nextInt(6);
        if (dado==0) {
            jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado 1.jpg")));
        } else if (dado==1) {
            jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado 2.jpg")));
        } else if (dado==2) {
            jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado 3.jpg")));
        } else if (dado==3) {
            jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado 4.jpg")));
        } else if (dado==4) {
            jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado 5.jpg")));
        } else if (dado==5) {
            jLbDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serpientesescaleras/interfazGrafica/images/dado 6.jpg")));
        }
        jBtnLanzar.setEnabled(true);
        jBtnDetener.setEnabled(false);
    }//GEN-LAST:event_jBtnDetenerActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jMenuItemJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJugadoresActionPerformed
        JugadoresFrm tabla = new JugadoresFrm();
        tabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemJugadoresActionPerformed

    private void jBtnCrearTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearTableroActionPerformed
        Tablero tablero = new Tablero(jPanel);
        tablero.crearMatriz(Integer.parseInt(jTxtNumFilas.getText()), Integer.parseInt(jTxtNumColumnas.getText()));
    }//GEN-LAST:event_jBtnCrearTableroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCrearTablero;
    private javax.swing.JButton jBtnDetener;
    private javax.swing.JButton jBtnLanzar;
    private javax.swing.JLabel jLbColumnas;
    private javax.swing.JLabel jLbDado;
    private javax.swing.JLabel jLbFilas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuIr;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemJugadores;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtNumColumnas;
    private javax.swing.JTextField jTxtNumFilas;
    // End of variables declaration//GEN-END:variables
}
